language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: YjUus4HwyAM1vARvO7gu5R5OcXVx7Bt38EDMnCKMxmMIA1Jg0U89N+iHXR8aquoKP5x0cuLY+L/W8EjsfqYFOJk87K95MxU8nHVnBRMwtzrkf3WZwFlKcbcNZq5z9/7QGY4DZXVKtYNkTFnvk/mxe3MpiLz3nUcW/BWe89ZWR3Bk+yfwJsxxoDfNfo40XzJugmYWBBKwDNJ3YEM2Qdm3WXOoTKV58jB15N36VuHsh6J1Q6LIJa+L5j9s+aW3FqVl4pxvpYInwvYJIRS9MCBIAh/l0P9E9rQ3cJF3or+3ncs6250+UFHtuJITtQ73S1KtpfkfjKsY3cPV4Uogrcrv9NAhpbXkIYEFVv+QqMajCviM1ort3JmC5dMJWYC2NEhpjnQdP+ntEe3/ybl7wJ+vMhb2tOGncsm4y/Lliyr+kgVcyKnZAWHXbWi5uJOG48KSFCa0lLj/DmjTctFamkD8p40PRsbFRXfepbHglFNRwjExV8PXYNiZYE4x23RfTAb0fYhxtszRbB7O/2y997GMwpXo8HbNtxx6M/u6yB4CXb+9hTm+keMnNJaIbRLQvefq5Jc/o8PFyWpPMIMnFDLz9cJmqZIFgH8Ox26a3zJRnLMDofWBH547c/wYI3HesqIZYq5l1ITlwFwTyHbfjCfIxDAJl7SfuFZBrtwute9FHtU=
